### ISSUE TITLE
HDF5 object as namespace

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/hatrac#7]
# Motivation
For several reasons, it might be useful to allow an HDF5 object to be exposed as a namespace in Hatrac:
1. An update of the HDF5 object to a new version can transactionally update all objects in its hierarchy, rather than having some appear before others.
2. With appropriate API support, the notion of a versioned namespace might be exposed such that a consistent view of older versions of the namespace remain online and referencable.
3. A large HDF5 archive could improve scalability:
  - Only one row in the Hatrac database for the whole HDF5 archive
  - Only one object in the underlying POSIX filesystem or S3 data store

# Challenges
However, there are several design issues to explore:
0. This is probably only feasible with POSIX backing store, not with S3 or another object store behind Hatrac.
1. Access should probably be read-only to maintain the basic object-store properties of Hatrac.
2. We would need to relax or abandon the idea that a particular hierarchical name cannot change from an object to a namepace or vice versa, since we cannot enforce namespace hygiene within the HDF5 file.
3. API extensions might be needed if we want to expose any HDF5 dataset or collection metadata.
4. An octet array dataset can be exposed trivially as a Hatrac object with byte slicing by HTTP range headers, but decisions would have to be made for other types of data.
  - Are they exposed as flattened octet streams?
  - Should multi-dimensional array slices be exposed with RESTful sub-resource URLs?

# Subtasks
- [ ] Spec out initial API extensions
- [ ] Prototype octet stream object access for 1-dimensional byte array datasets.
- [ ] Sanity-check performance to see if this is viable for practical applications.

**Comment by karlcz** [comment]
With the recent scalability improvements I don''t think HDF5 support is a high priority. We should probably migrate this to a wishlist.
